### ISSUE TITLE
I get this message when i click on map

### ISSUE THREAD

**Issue by flashing99** [AkashDivya/Explore-Flutter-FireStore#1]
![2019-08-16_03h46_49](https://user-images.githubusercontent.com/4593599/63140082-e4941400-bfe0-11e9-81a9-38147af4f834.png)

I/flutter ( 1082): Another exception was thrown: type 'String' is not a subtype of type 'double
thank you

**Comment by AkashDivya** [comment]
how can i recreate this error. was it there when it was started first time. please describe so that I can fix it.

And thnx brother for your input.

**Comment by AkashDivya** [comment]
I have personally checked the codes & files in this repo. I created a new project and copy-pasted all the files from here. Then I added my google-services.json from Firebase & added my Google Map API.
Everything is working fine brother.

You might have accidentally changed something. Redo all of the processes again. This was a false issue.
